version: "3"
services:
  server:
    build: /server
    container_name: server_c
    ports:
      - '3000:3000'
    volumes:
      - ./node_modules
  react:
    build: ./react
    container_name: react_c
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true